# Generated by Django 4.2.1 on 2023-06-18 08:30

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_location_alter_photo_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='pet_image',
            field=models.ImageField(upload_to='static/images', validators=[Petstagram.photos.validators.image_size_validator_5mb]),
        ),
    ]
